language: python
sudo: false
cache:
  directories:
  - "$HOME/.pip-cache/"
env:
  global:
  - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
  - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
python:
- '3.6'
addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev
install:
- pip wheel -r requirements.txt
- pip install .
script: pytest
deploy:
  provider: pypi
  user: mrahnis
  password:
    secure: 3Yb2BF518wScPnqztgsSkHfy4DFXLHbtOmYIoOfEX2dwT3g/6hDjq7+CWslt9vE/E7X77HKCwXdYc5cC4jkt/PK2qkA5mV9KTpMP6AxrBx2soCc35YBC8ozTyjMvArk5EUmo2KJ1WkQg1/Nfv2XkdvqBsMm93bDqAUK67BlQj8k+2lKhbuIUM4E4SYpKGlq3E9f9FQUWYbAW2AdvO9fuOX6dObO1PIMoCy2O3hc+kfY6O/ajm1/4pf8TWlO8Q7fD8k6onw1oDcWuavcyQPo18FFay81XSrDsWRSrBIaA97spCH8SyxhlgFDmbmgexMdXhrPhKoy1tsl2ITPn9xIG4ZNJeHtvYXfWVBrFePQQzZX9LxUJjcMq8etROU5D8FimCp0982o/f2wPpA8p1vVzrB/U2GznOnTHmeEVQIXtfhjcVagYBTylmIZN/YNnUpiC9xJpnv/XZpSWYQg9zcMvOr5E9wukVe3dMht+e2lbgHXI2OFezswRwSbJnknvOKIFTtotcxNJNRPXnX94DEMpMN4CK3XcANPlWtGD3ceo/MO168V4X5GcHKNQuxiJ+CoRrvj0tGtECquaFFTWmQiKjFoKHKVOqZOJ27ulQol8cuFWnzSY5NgqRAYpoLF+m34DzVa4izN3man9mj1iM8RmukbCvc9yp1kgk45tJoyAgNg=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: mrahnis/opusxml
  skip_cleanup: true
