language: python
sudo: false
cache:
  directories:
  - "$HOME/.pip-cache/"
env:
  global:
  - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
  - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
python:
- '3.7'
addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev
install:
- pip wheel -r requirements.txt
- pip install .
script: pytest
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: EH5esCDUO8NphNwY3a4zRxHQrQ5FV0msLL3k/pVFMIp3LFj0IkzFgOICLJi1auUipmgrqjL1vks+6HCZdPBNpXOish5YTHGIXyiy+ADgW1RBtQSp5j0ubspSG4D1vYtPVf6PmIAPjS9j6X9BNLpeteEBjxaQXPvyYv6BgwyUGKB5vHMCsFQKDXKwYpJa4j7hP0JI3L7gZ2OreH0PHImS/miQ98CRlV1uNY/jKmU0VSZeRpPOgsN92Bq6LuQapPhs4PytPPvTN9wz+YH6/J4vzIMWH4MNEeI988e0s1W+UFHcBdjUtiC5vvmah7sYQhaSOvyoM1FDNCoNHuzt5RJJfdelFe0a0RWPRvvA8Wb0qwBN5Fqy6/UzbLK7MYTq1KyQMxMaiysJ05aAxZVlMYh3pHqhx85EmJKQKbj9lv84abpe+HEQsDXkSaqmnc4PcWsbwQm+H65S1cv6x9hdbV7v1BTFoZEBqu7jvDhge7wJa8LfAKOd3tEvS5mwbny/b2DzYdqCrkE2hnotDtuZADmsuAMEiiPtVm1SpJnTZ5wT+E8zDBGGnUG2RvqlrXNTSrWL2S5LTuSkCDSwdfPzyNEecEqVF7iimvhKHto0gIblCwfaC2jbNAhrS+apa7ZIJIX3nMzA9/1vQt+TTEL3kcE64tqYvwzhAPiDZwQUQrGpE0c=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: mrahnis/opusxml
  skip_cleanup: true
