[project]
name = "opusxml"
version = "0.1.0"
description = "Add a short description here"
authors = ["mrahnis <mrahnis@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
lxml = ">=5.1.0,<5.2"
fiona = ">=1.9.5,<1.10"
pip = ">=23.3.2,<23.4"
setuptools = ">=69.0.3,<69.1"
click = ">=8.1.7,<8.2"
shapely = ">=2.0.2,<2.1"
pint = ">=0.23,<1"
