{% set pyproject = load_file_data('pyproject.toml') %}
{% set version = pyproject.get('project').get('version') %}


package:
  name: opusxml
  version: {{ version }}

source:
  git_url: https://github.com/mrahnis/opusxml.git
  git_rev: HEAD

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - opusxml = opusxml.cli.opusxml:cli
    
requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - click
    - lxml
    - pint 
    - shapely
    - fiona

test:
  imports:
    - opusxml
  commands:
    - opusxml --help

about:
  home: https://github.com/mrahnis/opusxml
  description: Python library to read and convert OPUSXML files
  license: BSD
  license_file: LICENSE.txt

# https://github.com/conda/conda-build/issues/4807
# whatever_you_do_don't_load_setup_py_dataxxx!!!